version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      PORT: 3001
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: yourpassword
      DB_NAME: todo_db
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:3001
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql-data:
